---
title: "Overinformativeness analysis"
output: html_document
---

To analyze the output of a webppl program for bayesian data analysis

```{r}
setwd("/Users/rxdh/Repos/overinformativeness/models/basic_level_reference/")

library(knitr)
opts_knit$set(root.dir = '/Users/rxdh/Repos/overinformativeness/models/basic_level_reference/')
library(ggplot2)
library(tidyr)
library(dplyr)
library(coda)
library(purrr)
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}
HPDhi<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}
HPDlo<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
options("scipen"=10) 
```

### Load in model results

```{r}
params<-read.csv("./bdaOutput/INTERPOLATEbdaOutputParams.csv", sep = ",", row.names = NULL)
samples = 10000
str(params)
params.samples <- params[rep(row.names(params), params$MCMCprob*samples), 1:2] 


paramHPDs = params.samples %>% 
  group_by(parameter) %>%
  summarize(md = estimate_mode(value),
            md_hi = round(HPDhi(value), 3),
            md_low = round(HPDlo(value), 3))
print(paramHPDs)
```

# Plot parameter posteriors

```{r}
ggplot(params.samples, aes(x=value)) +
    geom_histogram(data=subset(params.samples, parameter == "alpha"), 
                   binwidth = .5, colour="black", fill="white")+
    geom_histogram(data=subset(params.samples, parameter == "freqWeight"),
                   binwidth = .3, colour="black", fill="white")+
    geom_histogram(data=subset(params.samples, parameter == "lengthWeight"),
                 binwidth = .25, colour="black", fill="white")+
    geom_histogram(data=subset(params.samples, parameter == "typWeight"),
                 binwidth = .025, colour="black", fill="white")+

    geom_density(aes(y=.5*..count..), data =subset(params.samples, parameter == "alpha"), 
                 adjust = 3, alpha=.2, fill="#FF6666")+
    geom_density(aes(y=.3*..count..),data=subset(params.samples, parameter == "freqWeight"),
                 adjust = 3, alpha=.2, fill="#FF6666")+
    geom_density(aes(y=.25*..count..),data=subset(params.samples, parameter == "lengthWeight"),
                 adjust = 3.5, alpha=.2, fill="#FF6666")+
    geom_density(aes(y=.025*..count..),data=subset(params.samples, parameter== "typWeight"),
               adjust=2, alpha=.2, fill="#FF6666")+  

    ggtitle("Reference Parameter Posteriors (1000 iterations)") +
    facet_grid(~ parameter, scales = "free_x") +
    theme_bw()
```

### Predictives

# Import emp data

```{r}
source("rscripts/helpers.R")
d_allattr = read.csv("~/Repos/overinformativeness/experiments/4_numdistractors_basiclevel_newitems/results/noAttr.csv")

tmp = d_allattr %>%
  select(speakerMessages,condition,nameClickedObj,basiclevelClickedObj,
         superdomainClickedObj,typeMentioned,basiclevelMentioned,superClassMentioned,
         typeAttributeMentioned,basiclevelAttributeMentioned,superclassattributeMentioned)

# some cases are marked as having type and attribute mentions at different levels of the hierarchy. i'll interpret all mentions as type mentions of the highest compatible category
tmp$superMentioned = tmp$superClassMentioned | tmp$superclassattributeMentioned
tmp$basicMentioned = ifelse(!(tmp$superClassMentioned | tmp$superclassattributeMentioned) & (tmp$basiclevelMentioned | tmp$basiclevelAttributeMentioned),T,F)
tmp$subMentioned = !(tmp$superMentioned | tmp$basicMentioned)

agr = tmp %>%
  select(nameClickedObj,condition,basiclevelClickedObj,subMentioned,basicMentioned,superMentioned) %>%
  gather(Utterance, Mentioned,-condition,-basiclevelClickedObj,-nameClickedObj) %>%
  group_by(Utterance,condition,basiclevelClickedObj,nameClickedObj) %>%
  summarise(Probability=mean(Mentioned),
            cilow=ci.low(Mentioned),
            cihigh=ci.high(Mentioned)) %>%
  ungroup() %>%
  mutate(refLevel = factor(x = ifelse(Utterance == "subMentioned","sub",
                                      ifelse(Utterance == "basicMentioned","basic","super")),
                           levels=c("sub","basic","super"))) %>%
  mutate(target = nameClickedObj) %>%
  mutate(YMax = Probability + cihigh) %>%
  mutate(YMin = Probability - cilow) %>%
  select(condition, target, refLevel, Probability, YMax, YMin)
agr = as.data.frame(agr)
head(agr)

agr_allattr = agr
nrow(agr_allattr) # 432 datapoints
agr_allattr$condition = gsub("distr","item",as.character(agr_allattr$condition))
```

# combine with model fits, show by-target scatter

```{r}
predictive<-read.csv("./bdaOutput/INTERPOLATEbdaOutputPredictives.csv", sep = ",", row.names = NULL) 
predictive.samples <- predictive[rep(row.names(predictive), 
                                       predictive$MCMCprob*samples), 1:6] %>%
  mutate(refLevel = value) %>%
  group_by(refLevel, target, condition) %>%
  summarize(MAP = estimate_mode(prob),
            credHigh = HPDhi(prob),
            credLow = HPDlo(prob)) %>%
  inner_join(agr_allattr, by = c("refLevel", "target", "condition"))

ggplot(predictive.samples, aes(x=MAP,y=Probability,shape=condition,color=refLevel)) +
  geom_point() +
  xlim(c(0,1)) +
  ylim(c(0,1)) +
#  geom_errorbar(aes(ymax = YMax, ymin = YMin))+
#  geom_errorbarh(aes(xmax = credHigh, xmin = credLow)) +
  ylab("Empirical proportion") +
  xlab("Model predicted probability") +
  geom_abline(xintercept=0,yintercept=0,slope=1,color="gray60") #+
  #facet_wrap(~ domain)

cor(predictive.samples$MAP, predictive.samples$Probability)
ggsave("graphs/reparameterized/model_empirical_allattr_bydomain_multiplicative.pdf",width=8.4,height=6)
```


# Analyze at level of condition

```{r}
require(grid)
source("rscripts/helpers.R")
d_noattr = read.csv("~/Repos/overinformativeness/experiments/4_numdistractors_basiclevel_newitems/results/noAttr.csv")
d_noattr$nameClickedObj = as.character(d_noattr$nameClickedObj)
d_noattr$nameClickedObj = tolower(d_noattr$nameClickedObj)
d_noattr$nameClickedObj = as.factor(as.character(d_noattr$nameClickedObj))

tmp = d_noattr %>%
  select(speakerMessages,condition,nameClickedObj,basiclevelClickedObj,
         superdomainClickedObj,typeMentioned,basiclevelMentioned,superClassMentioned,
         typeAttributeMentioned,basiclevelAttributeMentioned,superclassattributeMentioned)

# some cases are marked as having type and attribute mentions at different levels of the hierarchy. i'll interpret all mentions as type mentions of the lowest compatible category
tmp[tmp$basiclevelMentioned & tmp$typeMentioned,]$basiclevelMentioned = F

agr = tmp %>%
  select(condition,typeMentioned,basiclevelMentioned,superClassMentioned) %>%
  gather(Utterance, Mentioned,-condition) %>%
  group_by(Utterance,condition) %>%
  summarise(Probability=mean(Mentioned),
            cilow=ci.low(Mentioned),
            cihigh=ci.high(Mentioned)) %>%
  ungroup() %>%
  mutate(refLevel = factor(x = ifelse(Utterance == "typeMentioned","sub",
                                      ifelse(Utterance == "basiclevelMentioned","basic","super")), levels=c("sub","basic","super"))) %>%
  mutate(YMax = Probability + cihigh) %>%
  mutate(YMin = Probability - cilow) %>%
  select(condition, refLevel, Probability, YMax, YMin)
agr = as.data.frame(agr)
head(agr)

agr_noattr = agr
nrow(agr_noattr) # 12 datapoints
agr_noattr$condition = gsub("distr","item",as.character(agr_noattr$condition))
agr_noattr$ModelType = "empirical"

predictive.samples <- predictive[rep(row.names(predictive), 
                                     predictive$MCMCprob*samples), 1:6] %>%
  mutate(refLevel = value) %>%
  group_by(refLevel, condition, target) %>%
  summarize(Prob = estimate_mode(prob),
            YMax = HPDhi(prob),
            YMin = HPDlo(prob)) %>%
  group_by(refLevel, condition) %>%
  summarize(Probability = mean(Prob),
            YMax = mean(Prob) + ci.high(Prob),
            YMin = mean(Prob) - ci.low(Prob))
predictive.samples = as.data.frame(predictive.samples)
predictive.samples$ModelType = "model"

toplot = merge(agr_noattr, predictive.samples, all=T)
#toplot = merge(toplot, predictive.samples.notyp, all=T)
#toplot = merge(toplot, predictive.samples.typ, all=T)

colors = scale_colour_brewer()[1:2]

ggplot(toplot, aes(x=condition,y=Probability,fill=ModelType)) +
  geom_bar(stat="identity",color="black") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) +
  scale_fill_brewer(guide=F) +
  ylab("Utterance probability") +
  xlab("Condition") +
  facet_grid(ModelType~refLevel) +
  theme(axis.text.x=element_text(angle=45,vjust=1,hjust=1),plot.margin=unit(c(0,0,0,0),"cm"))
```